import { suiteMeta } from '../../utils/suite'

/** Priority sources: FEMA NFHL + NWS + USGS + OpenFEMA (roadmap §6). */
export default defineEventHandler(() =>
  suiteMeta({
    layers: ['flood-risk', 'fema-nfhl', 'nws-alerts'],
    mapHubLayer: 'flood',
    defaultPort: 3013,
    dataPath: {
      now: [
        'FEMA NFHL MapServer layer 28 (Flood Hazard Zones)',
        'NWS active alerts (TX)',
        'demo zones for map pins / context',
      ],
      next: ['USGS NWIS gauges', 'OpenFEMA NFIP claims', 'NOAA ATLAS 14 precip'],
    },
    dataSources: [
      {
        id: 'fema-nfhl',
        name: 'FEMA NFHL ArcGIS',
        url: 'https://hazards.fema.gov/femaportal/wps/portal/NFHLWMS',
        auth: 'free',
        use: 'Official flood hazard zones',
        status: 'live',
        validation: 'very_high',
        confidence: 'official',
        cadence: 'as_published',
        demo: false,
      },
      {
        id: 'nws-alerts',
        name: 'NWS api.weather.gov',
        url: 'https://www.weather.gov/documentation/services-web-api',
        auth: 'free_user_agent',
        use: 'Active flood-related alerts',
        status: 'live',
        validation: 'high',
        confidence: 'official',
        cadence: 'real-time',
        demo: false,
      },
      {
        id: 'usgs-nwis',
        name: 'USGS Water Services',
        url: 'https://waterservices.usgs.gov/',
        auth: 'free',
        use: 'Stream gauges / streamflow',
        status: 'pending',
        validation: 'high',
        confidence: 'agency_open_data',
        cadence: 'real-time',
        demo: false,
      },
      {
        id: 'openfema-nfip',
        name: 'OpenFEMA datasets',
        url: 'https://www.fema.gov/about/openfema/data-sets',
        auth: 'free_rest',
        use: 'NFIP claims, disaster declarations',
        status: 'pending',
        validation: 'high',
        confidence: 'official',
        cadence: 'periodic',
        demo: false,
      },
      {
        id: 'zip-geocode',
        name: 'Zippopotam / Census',
        url: 'https://api.zippopotam.us/',
        auth: 'free',
        use: 'ZIP → lat/lon',
        status: 'live',
        validation: 'medium',
        confidence: 'agency_open_data',
        cadence: 'static',
        demo: false,
      },
      {
        id: 'demo-zones',
        name: 'Demo map pins',
        url: null,
        auth: 'n/a',
        use: 'Sample metro pins for browsing',
        status: 'live',
        validation: 'illustrative',
        confidence: 'modeled_demo',
        cadence: 'static',
        demo: true,
      },
    ],
    scrapingPolicy: {
      justified: [],
      possible: ['Local drainage layers if no official service'],
      forbidden: ['FEMA MSC HTML', 'weather.gov HTML', 'private insurer sites'],
    },
  }),
)
